version: '1.0'
build_version: 'v2'
stages:
  - prepare
  - build
  - push
steps:
  main_clone:
    title: Cloning repo
    type: git-clone
    repo: '${{CF_REPO_OWNER}}/${{CF_REPO_NAME}}'
    revision: '${{CF_REVISION}}'
    stage: prepare
    git: github
  build_docker_image:
    title: Building Docker image
    type: build
    stage: build
    buildkit: true
    progress: tty
    registry: ecr
    image_name: '${{CF_REPO_NAME}}'
    working_directory: ./
    dockerfile: Dockerfile
    tag: '${{CF_BRANCH_TAG_NORMALIZED}}'
  push_image:
    title: Push image to ECR
    type: push
    stage: push
    candidate: ${{build_docker_image}}
    registry: ecr
    image_name: '${{CF_REPO_NAME}}'
    tags:
      - '${{CF_BRANCH_TAG_NORMALIZED}}'
      - '${{CF_SHORT_REVISION}}'